local map = vim.keymap.set
local picker = Snacks.picker

-- Top Pickers & Explorer
map("n", "<leader><space>", function ()
  picker.smart()
end, { desc = "Smart Find Files" })
map("n", "<leader>,", function()
	picker.buffers()
end, { desc = "Buffers" })
map("n", "<leader>/", function()
	picker.grep()
end, { desc = "Grep" })
map("n", "<leader>:", function()
	picker.command_history()
end, { desc = "Command History" })
map("n", "<leader>n", function()
	Snacks.picker.notifications()
end, { desc = "Notification History" })
map("n", "<leader>e", function()
	Snacks.explorer()
end, { desc = "File Explorer" })

-- Find
map("n", "<leader>fb", function()
	picker.buffers()
end, { desc = "Buffers" })
map("n", "<leader>fc", function()
	picker.files({ cwd = vim.fn.stdpath("config") })
end, { desc = "Find Config File" })
map("n", "<leader>ff", function()
	picker.files()
end, { desc = "Find Files" })
map("n", "<leader>fg", function()
	picker.git_files()
end, { desc = "Find Git Files" })
map("n", "<leader>fp", function()
	picker.projects()
end, { desc = "Projects" })
map("n", "<leader>fr", function()
	picker.recent()
end, { desc = "Recent" })

-- Git
map("n", "<leader>gb", function()
	picker.git_branches()
end, { desc = "Git Branches" })
map("n", "<leader>gl", function()
	picker.git_log()
end, { desc = "Git Log" })
map("n", "<leader>gL", function()
	picker.git_log_line()
end, { desc = "Git Log Line" })
map("n", "<leader>gs", function()
	picker.git_status()
end, { desc = "Git Status" })
map("n", "<leader>gS", function()
	picker.git_stash()
end, { desc = "Git Stash" })
map("n", "<leader>gd", function()
	picker.git_diff()
end, { desc = "Git Diff (Hunks)" })
map("n", "<leader>gf", function()
	picker.git_log_file()
end, { desc = "Git Log File" })

-- GitHub
map("n", "<leader>gi", function()
	picker.gh_issue()
end, { desc = "GitHub Issues (open)" })
map("n", "<leader>gI", function()
	picker.gh_issue({ state = "all" })
end, { desc = "GitHub Issues (all)" })
map("n", "<leader>gp", function()
	picker.gh_pr()
end, { desc = "GitHub Pull Requests (open)" })
map("n", "<leader>gP", function()
	picker.gh_pr({ state = "all" })
end, { desc = "GitHub Pull Requests (all)" })

-- Grep / Search
map("n", "<leader>sb", function()
	picker.lines()
end, { desc = "Buffer Lines" })
map("n", "<leader>sB", function()
	picker.grep_buffers()
end, { desc = "Grep Open Buffers" })
map({ "n", "x" }, "<leader>sw", function()
	picker.grep_word()
end, { desc = "Visual selection or word" })
map("n", "<leader>sg", function()
	picker.grep()
end, { desc = "Grep" })
map("n", '<leader>s"', function()
	picker.registers()
end, { desc = "Registers" })
map("n", "<leader>s/", function()
	picker.search_history()
end, { desc = "Search History" })
map("n", "<leader>sa", function()
	picker.autocmds()
end, { desc = "Autocmds" })
map("n", "<leader>sc", function()
	picker.command_history()
end, { desc = "Command History" })
map("n", "<leader>sC", function()
	picker.commands()
end, { desc = "Commands" })
map("n", "<leader>sd", function()
	picker.diagnostics()
end, { desc = "Diagnostics" })
map("n", "<leader>sD", function()
	picker.diagnostics_buffer()
end, { desc = "Buffer Diagnostics" })
map("n", "<leader>sh", function()
	picker.help()
end, { desc = "Help Pages" })
map("n", "<leader>sH", function()
	picker.highlights()
end, { desc = "Highlights" })
map("n", "<leader>si", function()
	picker.icons()
end, { desc = "Icons" })
map("n", "<leader>sj", function()
	picker.jumps()
end, { desc = "Jumps" })
map("n", "<leader>sk", function()
	picker.keymaps()
end, { desc = "Keymaps" })
map("n", "<leader>sl", function()
	picker.loclist()
end, { desc = "Location List" })
map("n", "<leader>sm", function()
	picker.marks()
end, { desc = "Marks" })
map("n", "<leader>sM", function()
	picker.man()
end, { desc = "Man Pages" })
map("n", "<leader>sp", function()
	picker.lazy()
end, { desc = "Search for Plugin Spec" })
map("n", "<leader>sq", function()
	picker.qflist()
end, { desc = "Quickfix List" })
map("n", "<leader>sR", function()
	picker.resume()
end, { desc = "Resume" })
map("n", "<leader>su", function()
	picker.undo()
end, { desc = "Undo History" })
map("n", "<leader>uC", function()
	picker.colorschemes()
end, { desc = "Colorschemes" })

-- LSP
map("n", "gd", function()
	picker.lsp_definitions()
end, { desc = "Goto Definition" })
map("n", "gD", function()
	picker.lsp_declarations()
end, { desc = "Goto Declaration" })
map("n", "gr", function()
	picker.lsp_references()
end, { desc = "References", nowait = true })
map("n", "gI", function()
	picker.lsp_implementations()
end, { desc = "Goto Implementation" })
map("n", "gy", function()
	picker.lsp_type_definitions()
end, { desc = "Goto Type Definition" })
map("n", "gai", function()
	picker.lsp_incoming_calls()
end, { desc = "Calls Incoming" })
map("n", "gao", function()
	picker.lsp_outgoing_calls()
end, { desc = "Calls Outgoing" })
map("n", "<leader>ss", function()
	picker.lsp_symbols()
end, { desc = "LSP Symbols" })
map("n", "<leader>sS", function()
	picker.lsp_workspace_symbols()
end, { desc = "LSP Workspace Symbols" })

-- Misc / Utility
map("n", "<leader>z", function()
	Snacks.zen()
end, { desc = "Toggle Zen Mode" })
map("n", "<leader>Z", function()
	Snacks.zen.zoom()
end, { desc = "Toggle Zoom" })
map("n", "<leader>.", function()
	Snacks.scratch()
end, { desc = "Toggle Scratch Buffer" })
map("n", "<leader>S", function()
	Snacks.scratch.select()
end, { desc = "Select Scratch Buffer" })
map("n", "<leader>bd", function()
	Snacks.bufdelete()
end, { desc = "Delete Buffer" })
map("n", "<leader>cR", function()
	Snacks.rename.rename_file()
end, { desc = "Rename File" })
map({ "n", "v" }, "<leader>gB", function()
	Snacks.gitbrowse()
end, { desc = "Git Browse" })
map("n", "<leader>gg", function()
	Snacks.lazygit()
end, { desc = "Lazygit" })
map("n", "<leader>un", function()
	Snacks.notifier.hide()
end, { desc = "Dismiss All Notifications" })
map({ "n", "t" }, "]]", function()
	Snacks.words.jump(vim.v.count1)
end, { desc = "Next Reference" })
map({ "n", "t" }, "[[", function()
	Snacks.words.jump(-vim.v.count1)
end, { desc = "Prev Reference" })
map("n", "<c-/>", function()
	Snacks.terminal()
end, { desc = "Toggle Terminal" })
map("n", "<c-_>", function()
	Snacks.terminal()
end, { desc = "Toggle Terminal" })

-- Neovim News window
map("n", "<leader>N", function()
	Snacks.win({
		file = vim.api.nvim_get_runtime_file("doc/news.txt", false)[1],
		width = 0.6,
		height = 0.6,
		wo = {
			spell = false,
			wrap = false,
			signcolumn = "yes",
			statuscolumn = " ",
			conceallevel = 3,
		},
	})
end, { desc = "Neovim News" })
