vim.o.number = true
vim.o.relativenumber = false
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.shiftwidth = 2
vim.o.tabstop = 2
vim.o.swapfile = false
vim.g.mapleader = " "
vim.g.maplocalleader = " "
